#!/bin/bash
set -e

uid=$(id -u)
gid=$(id -g)
shifts=0

function set_ids {
    if [[ "$1" == "--uid" || "$1" == "--gid" ]]; then
	if [[ "$1" == "--uid" ]]; then
	    uid="$2"
	    shifts=$(($shifts + 2))
	    shift; shift
	    set_ids "$@"
	    return
	fi
	if [[ "$1" == "--gid" ]]; then
	    gid="$2"
	    shifts=$(($shifts + 2))
	    shift; shift
	    set_ids "$@"
	fi
    fi   
}
set_ids "$@"

for i in $(seq 1 $shifts); do
    shift
done

image=emacs-elpy-${uid}-${gid}
if [ -z "$(docker images | grep ${image})" ]; then
    tmpdir=$(mktemp -d)
    echo "FROM mbodenhamer/emacs-elpy:latest" > ${tmpdir}/Dockerfile
    docker build -t ${image}:latest --build-arg uid=$uid \
	--build-arg gid=$gid $tmpdir
    rm -rf $tmpdir
fi

if [[ -n $(which xhost) ]]; then
    xhost +local:docker
fi
docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY \
    -v $(pwd):/files ${image} "$@"
